# Generated by Django 4.2.16 on 2024-11-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_image_carmodel_unique_car_model_per_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='image',
        ),
    ]
