# Generated by Django 4.2.16 on 2024-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_carmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
