# Generated by Django 4.2.16 on 2024-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, default='images/sample.jpg', null=True, upload_to='images/'),
        ),
    ]
